Require Django version < 2.0 for now (otherwise tests fail)
Error with Django 2.0:
  File ".../wq.db/.eggs/python_social_auth-0.2.21-py3.4.egg/social/apps/django_app/default/models.py", line 33, in AbstractUserSocialAuth
      user = models.ForeignKey(USER_MODEL, related_name='social_auth')
  TypeError: __init__() missing 1 required positional argument: 'on_delete'